# Site settings
title: Richard Kelley
description: "AI and Robotics."
url: "http://richardkelley.github.io"
author:
  name: "Richard Kelley"
  email: "richard.kelley@gmail.com"
  url: "https://www.richardkelley.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
include:
  - _posts/2026-02-16-llm-training/llm-training-2026.jpg

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "0.0.1"

# Options
custom_header: true
custom_nav_footer: false
reverse: false

gems: [jekyll-paginate]
